# Test Locators
ACCOUNT_XPH = '//*[@class="fa fa-user"]'
SUBMIT_XPH = '//*[@class="woocommerce-Button button"]'
REGISTER_XPH = '//*[@id="customer_login"]/div[2]/form/p[3]/input[3]'
REGISTRATION_NAME_XPH = '//*[@class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required"]'
REGISTRATION_EMAIL_XPH = '//*[@class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"]'
SUBJECT_XPH = '//*[@class="wpcf7-form-control wpcf7-text"]'
MESSAGE_XPH = '//*[@class="wpcf7-form-control wpcf7-textarea"]'
SEND_MSG_XPH = '//*[@class="wpcf7-form-control wpcf7-submit"]'
SEARCH_XPH = '//*[@class="search-field-top-bar"]'
SEARCH_TAB_XPH = '//*[@class="fa fa-search"]'
MAIN_XPH = '//*[@class="site-title"]'
SUBSCRIBE_XPH = '//*[@class="es_textbox_button es_submit_button"]'
TAGS_XPH = '//*[@id="tag_cloud-1"]/div/a[1]'
POST_XPH = '//*[@id="recent-posts-2"]/ul/li[1]/a'